title: CHIJ St Nicholas Girls' School (Primary)
url: https://chijstnicholasgirls.moe.edu.sg
favicon: /images/logo.png
colors:
  primary-color: "#064f93"
  secondary-color: "#b93737"
  media-colors:
    - title: media-color-one
      color: "#71b4f3"
    - title: media-color-two
      color: "#f49090"
    - title: media-color-three
      color: "#a4ccf1"
    - title: media-color-four
      color: "#f3c6c6"
    - title: media-color-five
      color: "#a6afef"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d6ffahuouz5lv.amplifyapp.com
prod: https://master.d6ffahuouz5lv.amplifyapp.com
shareicon: /images/logo.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: chij-pri
